
services:
  elasticsearch:
    image: elasticsearch:7.17.10
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - elk_net
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200 || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 10

  logstash:
    image: logstash:7.17.10
    environment:
      - "LS_JAVA_OPTS=-Xms256m -Xmx256m"
    volumes:
      - .:/app
      - ./waf_elk/filebeat_logstash.conf:/usr/share/logstash/pipeline/filebeat_logstash.conf
    ports:
      - "5044:5044"
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - elk_net

  kibana:
    image: kibana:7.17.10
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - elk_net

  modsec_crs:
    build:
      context: ./waf_modsec/
      dockerfile: Dockerfile
    ports:
      - "9091:8080"
      - "8000:8000"
      - "8888:8888"
    environment:
      - PARANOIA=5
    volumes:
      - .:/app
    depends_on:
      elasticsearch:
        condition: service_healthy
    privileged: true
    networks:
      - elk_net

networks:
  elk_net:
    driver: bridge

volumes:
  esdata:
    driver: local
