# --- CHAMELEON-REN CRS Setup ---
# Engine is already set to DetectionOnly via Dockerfile ENV

SecAction \
 "id:900000,\
  phase:1,\
  nolog,\
  pass,\
  t:none,\
  setvar:tx.paranoia_level=1"