# Custom Health Check Endpoint
Alias /healthz /var/www/html/healthz.txt

<Directory "/var/www/html">
    Require all granted
</Directory>

# Don't log health checks so we don't spam our own logs
SetEnvIf Request_URI "^/healthz$" dontlog
CustomLog /usr/local/apache2/logs/access.log combined env=!dontlog