elk:
  image: sebp/elk
  ports:
    - "5601:5601"
    - "9200:9200"
    - "5044:5044"
  volumes:
    - ./:/app
    
modsec_crs:
  image: owasp/modsecurity-crs
  ports:
    - "80:80"
  environment:
    - PARANOIA=5
  volumes:
    - ./:/app

