services:
  modsec_crs:
    env_file:
      - ./env
    ports:
      - "9091:80"
      - "8000:8000"
      - "8080:8080"
      - "8888:8888"
    environment:
      - PARANOIA=5
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    build: ./
    container_name: modsec_app
    depends_on:
      - persona-generic

  persona-generic:
    image: nginx:alpine
    container_name: persona-generic
    volumes:
      - ./personas/generic:/usr/share/nginx/html:ro
    profiles:
      - generic

  persona-wordpress:
    image: wordpress:5.8.1-php7.4-apache
    container_name: persona-wordpress
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
    profiles:
      - wordpress

  persona-drupal:
    image: drupal:7.91-php7.4-apache
    container_name: persona-drupal
    profiles:
      - drupal

  db:
    image: mysql:5.7
    container_name: persona-db
    environment:
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
      - MYSQL_ROOT_PASSWORD=rootpassword
    profiles:
      - wordpress
