include "/etc/modsecurity.d/modsecurity.conf"
include /etc/modsecurity.d/owasp-crs/crs-setup.conf
includeOptional /etc/modsecurity.d/owasp-crs/plugins/*-config.conf
includeOptional /etc/modsecurity.d/owasp-crs/plugins/*-before.conf
include /etc/modsecurity.d/owasp-crs/rules/*.conf
includeOptional /etc/modsecurity.d/owasp-crs/plugins/*-after.conf
