elk:
  env_file:
    - ./env
  ports:
    - "5601:5601"
    - "9200:9200"
    - "5044:5044"
  volumes:
    - .:/app
  environment:
  - LOGSTASH_START=1
  - PIPENV_VENV_IN_PROJECT=true
  build: ./
  container_name: elk_app
