version: "3"
services:
  misp_push:
    container_name: misp_push
    networks:
      - elastic
    volumes:
      - ./misp-push:/app
    env_file:
      - ./misp-push/env
    build: ./misp-push/
    command: /app/start.sh
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
    restart: always
    extra_hosts:
      - "elasticsearch:<ELASTIC IP ADDRESS>"
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.5.1
    ports:
    - "9200:9200"
    - "9300:9300"
    environment:
      - node.name=elasticsearch
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - discovery.seed_hosts=elasticsearch
      #- logger.transport.level=trace
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    extra_hosts:
      - "elasticsearch:<ELASTIC IP ADDRESS>"
    networks:
      - elastic
  kibana:
    container_name: kibana
    image: kibana:7.5.1
    ports:
      - "5601:5601"
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
    extra_hosts:
      - "elasticsearch:<ELASTIC IP ADDRESS>"
    networks:
      - elastic
  logstash:
    container_name: logstash
    links:
      - elasticsearch
    ports:
      - "5044:5044"
    volumes:
      - ./logstash:/app
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    build: ./logstash
    depends_on:
    - elasticsearch
    environment:
    - PIPENV_VENV_IN_PROJECT=true
    command: logstash
    extra_hosts:
      - "elasticsearch:<ELASTIC IP ADDRESS>"
    networks:
      - elastic

networks:
  elastic:
    driver: bridge