worker_processes auto;

events {
    worker_connections 1024;
}

http {
    server_tokens off;
    
    # DoS Protection: Limit to 10 requests per second per IP
    limit_req_zone $binary_remote_addr zone=honeypot_limit:10m rate=10r/s;

    server {
        listen 80;
        server_name localhost;

        # ==========================================
        # AWS & DOCKER IP FIX (real_ip module)
        # ==========================================
        # Tells Nginx to extract the true attacker IP from the X-Forwarded-For header
        # instead of using the internal Docker/AWS Load Balancer IP (172.x.x.x)
        set_real_ip_from 0.0.0.0/0;
        real_ip_header X-Forwarded-For;

        location / {
            limit_req zone=honeypot_limit burst=20 nodelay;

            # ==========================================
            # 1. ROUTE TO THE PYTHON BRAIN
            # ==========================================
            # Nginx passes all traffic to the Stimulus Engine first
            proxy_pass http://engine:5000;
            
            # ==========================================
            # 2. PRESERVE ATTACKER IDENTITY
            # ==========================================
            # Crucial for the Python Engine to read the real IP and User-Agent
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header User-Agent $http_user_agent;

            # ==========================================
            # 3. HEADER SPOOFING
            # ==========================================
            # Disguise the proxy to look like a standard web server
            proxy_hide_header Server;
            proxy_hide_header X-Powered-By;
            # add_header Server "nginx/1.24.0" always;
            # add_header X-Powered-By "PHP/8.2" always;
        }
    }
}
