name: WAF ModSec Tests

on:
  push:
    paths:
      - 'honeytraps/waf_modsec/**'
  pull_request:
    paths:
      - 'honeytraps/waf_modsec/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and test
        working-directory: honeytraps/waf_modsec
        run: |
          cp sample-env env
          bash run_tests.sh
